import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ToastContainer } from "react-toastify";
import TokenHandler from "@/components/TokenHandler";
import MainProvider from "@/NoSSRProvider/MainProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <ToastContainer />
        <div className="max-w-[1600px] mx-auto">
          <MainProvider>
            <Navbar />
            <TokenHandler />
            {children}
          </MainProvider>
        </div>
        {/* </MainProvider>
        </Nossr> */}
      </body>
    </html>
  );
}
